### ISSUE TITLE
Unable to get property 'attachToForm' of undefined or null refernece in IE10

### ISSUE THREAD

**Issue by veerumandli** [NewOldMax/react-material-ui-form-validator#22] opened 2017-07-06 07:32 UTC
Unable to get property 'attachToForm' of undefined or null reference in IE10 due to that my entire application it self it showing blank screen.

Can please suggest any dependency package need to be required for IE.

**Comment by NewOldMax** [comment] 2017-07-06 08:05
Duplicate of #21 
As I said, IE10 and below is not goal of this library. 
Since Microsoft doesn't support updates for IE10, I don't see any reasons to support this browser.

You can clone this library and play around with it. Maybe upgrading babel tools can help with it. As I see babel has some [fixes](https://github.com/babel/babel/pull/3527) for it.

**Closed by NewOldMax** 2017-07-06 08:05 UTC
