### ISSUE TITLE
Extending ValidatorComponent for a Custom component no longer works with latest version

### ISSUE THREAD

**Issue by zachrickards** [NewOldMax/react-material-ui-form-validator#147] opened 2020-08-12 13:04 UTC
When extending a class with ValidatorComponent the form object is not passed and causes attachToForm and detachToForm errors. Please provide a new example of a custom validator?

**Comment by NewOldMax** [comment] 2020-08-12 13:08
Hi @zachrickards 
you can see an example in the Readme section (simply just replace `render` method with `renderValidatorComponent` in your custom component)
duplicate of #146

**Closed by NewOldMax** 2020-08-12 13:08 UTC

**Comment by zachrickards** [comment] 2020-08-12 13:20
@NewOldMax Thanks for the quick response and apologize for the duplicate
