### ISSUE TITLE
matchRegexp doesn't seam to work

### ISSUE THREAD

**Issue by agjs** [NewOldMax/react-material-ui-form-validator#118] opened 2019-09-03 11:32 UTC
Hey there and thanks for maintaining the library. I'm trying to use the matchRegexp prop but it doesn't seam to be working, here is the test scenario:

```js
var str = '123456-1234';

var regex = RegExp(/^\d{6}-?[a-zA-Z\d]{3}\d$/gm);

console.log(regex.test(str));
// expected output: true
```

This is exactly what I have inside of the validators:

```
validators={[`matchRegexp: /^\d{6}-?[a-zA-Z\d]{3}\d$/gm`]}
```

Thanks in advance :)

**Comment by FroggDev** [comment] 2019-09-03 11:58
regexp string is without delimiter :
`matchRegexp:^\d{6}-?[a-zA-Z\d]{3}\d$`

**Comment by agjs** [comment] 2019-09-03 12:22
It doesn't seam to be working. :/

**Comment by NewOldMax** [comment] 2019-09-03 12:24
Duplicate of #58

**Closed by NewOldMax** 2019-09-03 12:24 UTC
